### ISSUE TITLE
Replace actions-rs/toolchain action

### ISSUE THREAD

**Issue by JohnTitor** [rust-netlink/.github#3]
On CI we use actions-rs/toolchain but it's currently unmaintained and has some issues like https://github.com/actions-rs/toolchain/pull/220.
An alternative in my mind is https://github.com/dtolnay/rust-toolchain or using toolchains on GHA directly.
Does someone have any objections? If not, I'm going to replace them on the repos under the org.

**Comment by cathay4t** [comment]
I noticed alacritty is using `rustup` directly. Maybe we should the same.

**Comment by cathay4t** [comment]
Closing as all work finished.
